Library_Cet322/Models/Catalog/AssetIndexListingModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryCet322.Models.Catalog
{
    public class AssetIndexListingModel
    {
        public int Id { get; set; }
        public string ImageUrl { get; set; }
        public string Title { get; set; }
        public string AuthorOrDirector { get; set; }
        public string DeweyCallNumber { get; set; }
        public string NumberOfCopies { get; set; }
        public string Type { get; internal set; }
    }
}

Library_Cet322/Models/Catalog/AssetIndexModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryCet322.Models.Catalog
{
    public class AssetIndexModel
    {
        public IEnumerable<AssetIndexListingModel> Assets { get; set; }
    }
}

Library_Cet322/Controllers/CatalogController.cs
using ClassLibrary1;
using LibraryCet322.Models.Catalog;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace LibraryCet322.Controllers
{
    public class CatalogController : Controller
    {
        private ILibraryAsset _assets;
        public CatalogController(ILibraryAsset assets)
            {
            _assets = assets;
            }
        public  IActionResult Index()
        {
            var assetModels = _assets.GetAll();
            var listingResult = assetModels
                .Select(result => new AssetIndexListingModel

                {
                    Id = result.Id,
                    ImageUrl = result.ImageUrl,
                    AuthorOrDirector = _assets.GetAuthorOrDirector(result.Id),
                    DeweyCallNumber = _assets.GetDeweyIndex(result.Id),
                    Title = result.Title,
                    Type = _assets.GetType(result.Id)
                });

            var model = new AssetIndexModel()
            {
                Assets = listingResult
            };

            return View(model);
        }
    }
}

Library_Cet322/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace LibraryCet322.Controllers
{
    public class HomeController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "My application description page.";

            return View();
        }

     
        public IActionResult Contact()
        {

            ViewData["Message"] = "My contact page.";

            return View();
        }
        public IActionResult Error()
        {

      return View();
        }
    }
}

Library_Cet322/Views/Home/Index.cshtml
@model LibraryCet322.Models.Catalog.AssetIndexModel

<div id="assets">
    <h3>Library Catalog</h3>
    <div id="assetsTable">
        <table class="table tab-condensed" id="catalogIndexTable">
            <thead>
                <tr>
                    <th>Image</th>
                    <th>Title</th>
                    <th>Author / Director </th>
                    <th>Dewey Call Number </th>
                </tr>
            </thead>
            <tbody>
                @*@foreach (var asset in  Model.Assets)
                    {
                        <tr class="assetRow">
                            <td class="">
                                <a asp-controller="Catalog" asp-action="Detail" asp-route-id="@asset.Id" >
                                  <img src="@asset.ImageUrl" class="imageCell" />
                                </a>
                            </td>
                            <td class="">@asset.Title</td>
                            <td class="">@asset.AuthorOrDirector</td>
                            <td class="">@asset.DeweyCallNumber</td>
                        </tr>
                    }*@



            </tbody>
        </table>
    </div>
</div>

Library_Cet322/Views/Shared/_Layout.cshtml
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Library_Cet322</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Library_Cet322</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Library_Cet322 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</>